swagger: "2.0"
info:
    title: DVC Points Calculator
    description: Backend service for DVC Points Calculator UI
    version: ""
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /resort:
        get:
            tags:
                - dvcPointsCalculator
            summary: GetResorts dvcPointsCalculator
            operationId: dvcPointsCalculator#GetResorts
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DvcPointsCalculatorDvcpointcalculatorResortResponseCollection'
            schemes:
                - http
    /resort/{resortCode}:
        get:
            tags:
                - dvcPointsCalculator
            summary: GetResort dvcPointsCalculator
            operationId: dvcPointsCalculator#GetResort
            parameters:
                - name: resortCode
                  in: path
                  description: the resort's code
                  required: true
                  type: string
                  pattern: '[a-z]{3}'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DvcPointsCalculatorGetResortResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/DvcPointsCalculatorGetResortNotFoundResponseBody'
            schemes:
                - http
definitions:
    DvcPointsCalculatorDvcpointcalculatorResortResponseCollection:
        title: 'Mediatype identifier: application/vnd.dvcpointcalculator.resort; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/DvcpointcalculatorResortResponse'
        description: GetResortsResponseBody is the result type for an array of DvcpointcalculatorResortResponse (default view)
        example:
            - code: ssr
              name: Disney's Saratoga Springs Resort & Spa
              roomTypes:
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
            - code: ssr
              name: Disney's Saratoga Springs Resort & Spa
              roomTypes:
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
            - code: ssr
              name: Disney's Saratoga Springs Resort & Spa
              roomTypes:
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
            - code: ssr
              name: Disney's Saratoga Springs Resort & Spa
              roomTypes:
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
    DvcPointsCalculatorGetResortNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: GetResort_not_found_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    DvcPointsCalculatorGetResortResponseBody:
        title: 'Mediatype identifier: application/vnd.dvcpointcalculator.resort; view=default'
        type: object
        properties:
            code:
                type: string
                description: resort's code
                example: ssr
                pattern: '[a-z]{3}'
            name:
                type: string
                description: resort's name
                example: Disney's Saratoga Springs Resort & Spa
            roomTypes:
                type: array
                items:
                    $ref: '#/definitions/RoomTypeResponseBody'
                example:
                    - bedrooms: 1
                      beds: 3
                      code: 1bp
                      name: One Bedroom Villa (Preferred View)
                      sleeps: 5
                    - bedrooms: 1
                      beds: 3
                      code: 1bp
                      name: One Bedroom Villa (Preferred View)
                      sleeps: 5
                    - bedrooms: 1
                      beds: 3
                      code: 1bp
                      name: One Bedroom Villa (Preferred View)
                      sleeps: 5
                    - bedrooms: 1
                      beds: 3
                      code: 1bp
                      name: One Bedroom Villa (Preferred View)
                      sleeps: 5
        description: GetResortResponseBody result type (default view)
        example:
            code: ssr
            name: Disney's Saratoga Springs Resort & Spa
            roomTypes:
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
    DvcpointcalculatorResortResponse:
        title: 'Mediatype identifier: application/vnd.dvcpointcalculator.resort; view=default'
        type: object
        properties:
            code:
                type: string
                description: resort's code
                example: ssr
                pattern: '[a-z]{3}'
            name:
                type: string
                description: resort's name
                example: Disney's Saratoga Springs Resort & Spa
            roomTypes:
                type: array
                items:
                    $ref: '#/definitions/RoomTypeResponse'
                example:
                    - bedrooms: 1
                      beds: 3
                      code: 1bp
                      name: One Bedroom Villa (Preferred View)
                      sleeps: 5
                    - bedrooms: 1
                      beds: 3
                      code: 1bp
                      name: One Bedroom Villa (Preferred View)
                      sleeps: 5
                    - bedrooms: 1
                      beds: 3
                      code: 1bp
                      name: One Bedroom Villa (Preferred View)
                      sleeps: 5
                    - bedrooms: 1
                      beds: 3
                      code: 1bp
                      name: One Bedroom Villa (Preferred View)
                      sleeps: 5
        description: DvcpointcalculatorResortResponse result type (default view)
        example:
            code: ssr
            name: Disney's Saratoga Springs Resort & Spa
            roomTypes:
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
                - bedrooms: 1
                  beds: 3
                  code: 1bp
                  name: One Bedroom Villa (Preferred View)
                  sleeps: 5
    RoomTypeResponse:
        title: RoomTypeResponse
        type: object
        properties:
            bedrooms:
                type: integer
                description: number of bedrooms
                example: 1
                format: int64
            beds:
                type: integer
                description: number of beds
                example: 3
                format: int64
            code:
                type: string
                description: room type's code
                example: 1bp
                pattern: '[a-z0-9]{3}'
            name:
                type: string
                description: room type's name
                example: One Bedroom Villa (Preferred View)
            sleeps:
                type: integer
                description: max room capacity
                example: 5
                format: int64
        example:
            bedrooms: 1
            beds: 3
            code: 1bp
            name: One Bedroom Villa (Preferred View)
            sleeps: 5
    RoomTypeResponseBody:
        title: RoomTypeResponseBody
        type: object
        properties:
            bedrooms:
                type: integer
                description: number of bedrooms
                example: 1
                format: int64
            beds:
                type: integer
                description: number of beds
                example: 3
                format: int64
            code:
                type: string
                description: room type's code
                example: 1bp
                pattern: '[a-z0-9]{3}'
            name:
                type: string
                description: room type's name
                example: One Bedroom Villa (Preferred View)
            sleeps:
                type: integer
                description: max room capacity
                example: 5
                format: int64
        example:
            bedrooms: 1
            beds: 3
            code: 1bp
            name: One Bedroom Villa (Preferred View)
            sleeps: 5
